DECLARE @marca CHAR(4) = 'DUN'

DECLARE @productos TABLE (
	CODIGO VARCHAR (25),
	PRODUCTO VARCHAR (60),
	MARCA VARCHAR (60),
	MODELO VARCHAR (60), 
	JCH_STOCK INT,  JCH_VENTAS INT,
	EVO_STOCK INT, EVO_VENTAS INT,
	NEU_STOCK INT, NEU_VENTAS INT
)

INSERT INTO @productos
SELECT rtrim(ltrim(A.AR_CCODIGO)) CODIGO , RTRIM(LTRIM(A.AR_CDESCRI)) PRODUCTO, ltrim(rtrim(MA.TG_CDESCRI)) MARCA, ltrim(rtrim(MO.TG_CDESCRI)) MODELO,
0 JCH_STOCK, 0 JCH_VENTAS, 
0 EVO_STOCK,  0 EVO_VENTAS, 
0 NEU_STOCK, 0 NEU_VENTAS
FROM JCHS2018..al0001arti A 
LEFT JOIN JCHS2018..AL0001TABL MA ON MA.TG_CCOD='V7' AND MA.TG_CCLAVE=A.AR_CMARCA 
LEFT JOIN JCHS2018..AL0001TABL MO ON MO.TG_CCOD='39' AND MO.TG_CCLAVE=A.AR_CMODELO 
LEFT JOIN JCHS2018..FT0001LINE L ON A.AR_CLINEA=L.LI_CCODLIN 
WHERE A.AR_CMARCA=@marca AND L.LI_COBSER2 LIKE '%NEUMA%' 
ORDER BY A.AR_CCODIGO, A.AR_CDESCRI 


-- TABLA TEMPORAL 
DECLARE @stock TABLE ( CODIGO VARCHAR (25), STOCK INT)


-- STOCK JCH
INSERT INTO @stock
SELECT A.AR_CCODIGO, SUM(SK_NSKDIS) FROM JCHS2018..AL0001STOC S
LEFT JOIN JCHS2018..AL0001ARTI A ON AR_CMARCA=@marca AND A.AR_CCODIGO=S.SK_CCODIGO
GROUP BY A.AR_CCODIGO

UPDATE t SET t.JCH_STOCK = ISNULL(t2.STOCK,0) FROM @productos t 
LEFT JOIN @stock t2 ON t.CODIGO=t2.CODIGO
DELETE @stock

-- STOCK EVOCAR
INSERT INTO @stock
SELECT A.AR_CCODIGO, SUM(SK_NSKDIS) FROM CARS2018..AL0001STOC S
LEFT JOIN JCHS2018..AL0001ARTI A ON AR_CMARCA=@marca AND A.AR_CCODIGO=S.SK_CCODIGO
GROUP BY A.AR_CCODIGO

UPDATE t SET t.EVO_STOCK = ISNULL(t2.STOCK,0)FROM @productos t 
LEFT JOIN @stock t2 ON t.CODIGO=t2.CODIGO
DELETE @stock


-- STOCK NEUMACENTER
INSERT INTO @stock
SELECT A.AR_CCODIGO, SUM(SK_NSKDIS) FROM NEUS2018..AL0001STOC S
LEFT JOIN JCHS2018..AL0001ARTI A ON AR_CMARCA=@marca AND A.AR_CCODIGO=S.SK_CCODIGO
GROUP BY A.AR_CCODIGO

UPDATE t SET t.NEU_VENTAS= ISNULL(t2.STOCK,0)FROM @productos t 
LEFT JOIN @stock t2 ON t.CODIGO=t2.CODIGO
DELETE @stock


-- VENTAS JCH
INSERT INTO @stock
SELECT A.AR_CCODIGO CODIGO, SUM(s.F6_NCANTID) VENTAS
FROM (SELECT F6_CTD, F6_CNUMSER, F6_CNUMDOC, F6_CCODIGO, F6_NCANTID FROM JCHS2018..FT0001ACUD 
UNION ALL SELECT F6_CTD, F6_CNUMSER, F6_CNUMDOC, F6_CCODIGO, F6_NCANTID FROM JCHS2018..FT0001FACD
) S
LEFT JOIN (SELECT F5_CTD, F5_CNUMSER, F5_CNUMDOC, F5_DFECDOC, F5_CFORVEN, F5_CESTADO FROM JCHS2018..FT0001ACUC 
UNION ALL SELECT F5_CTD, F5_CNUMSER, F5_CNUMDOC, F5_DFECDOC, F5_CFORVEN, F5_CESTADO FROM JCHS2018..FT0001FACC
) C
ON C.F5_CTD=S.F6_CTD AND C.F5_CNUMSER=S.F6_CNUMSER AND C.F5_CNUMDOC=S.F6_CNUMDOC
LEFT JOIN JCHS2018..AL0001ARTI A ON S.F6_CCODIGO=a.AR_CCODIGO
WHERE C.F5_CESTADO<>'A' AND S.F6_CTD IN ('FT','BV')
AND YEAR(C.F5_DFECDOC)=2018 AND A.AR_CMARCA=@marca 
AND NOT C.F5_CFORVEN IN ('O','P')
GROUP BY A.AR_CCODIGO

UPDATE t SET t.JCH_VENTAS= ISNULL(t2.STOCK,0)FROM @productos t 
LEFT JOIN @stock t2 ON t.CODIGO=t2.CODIGO
DELETE @stock



-- VENTAS EVOCAR
INSERT INTO @stock
SELECT A.AR_CCODIGO CODIGO, SUM(s.F6_NCANTID) VENTAS
FROM (SELECT F6_CTD, F6_CNUMSER, F6_CNUMDOC, F6_CCODIGO, F6_NCANTID FROM CARS2018..FT0001ACUD 
UNION ALL SELECT F6_CTD, F6_CNUMSER, F6_CNUMDOC, F6_CCODIGO, F6_NCANTID FROM CARS2018..FT0001FACD
) S
LEFT JOIN (SELECT F5_CTD, F5_CNUMSER, F5_CNUMDOC, F5_DFECDOC, F5_CFORVEN, F5_CESTADO FROM CARS2018..FT0001ACUC 
UNION ALL SELECT F5_CTD, F5_CNUMSER, F5_CNUMDOC, F5_DFECDOC, F5_CFORVEN, F5_CESTADO FROM CARS2018..FT0001FACC
) C
ON C.F5_CTD=S.F6_CTD AND C.F5_CNUMSER=S.F6_CNUMSER AND C.F5_CNUMDOC=S.F6_CNUMDOC
LEFT JOIN JCHS2018..AL0001ARTI A ON S.F6_CCODIGO=a.AR_CCODIGO
WHERE C.F5_CESTADO<>'A' AND S.F6_CTD IN ('FT','BV')
AND YEAR(C.F5_DFECDOC)=2018 AND A.AR_CMARCA=@marca 
AND NOT C.F5_CFORVEN IN ('O','P')
GROUP BY A.AR_CCODIGO

UPDATE t SET t.EVO_VENTAS= ISNULL(t2.STOCK,0)FROM @productos t 
LEFT JOIN @stock t2 ON t.CODIGO=t2.CODIGO
DELETE @stock


-- VENTAS NEUMACENTER
INSERT INTO @stock
SELECT A.AR_CCODIGO CODIGO, SUM(s.F6_NCANTID) VENTAS
FROM (SELECT F6_CTD, F6_CNUMSER, F6_CNUMDOC, F6_CCODIGO, F6_NCANTID FROM NEUS2018..FT0001ACUD 
UNION ALL SELECT F6_CTD, F6_CNUMSER, F6_CNUMDOC, F6_CCODIGO, F6_NCANTID FROM NEUS2018..FT0001FACD
) S
LEFT JOIN (SELECT F5_CTD, F5_CNUMSER, F5_CNUMDOC, F5_DFECDOC, F5_CFORVEN, F5_CESTADO FROM NEUS2018..FT0001ACUC 
UNION ALL SELECT F5_CTD, F5_CNUMSER, F5_CNUMDOC, F5_DFECDOC, F5_CFORVEN, F5_CESTADO FROM NEUS2018..FT0001FACC
) C
ON C.F5_CTD=S.F6_CTD AND C.F5_CNUMSER=S.F6_CNUMSER AND C.F5_CNUMDOC=S.F6_CNUMDOC
LEFT JOIN JCHS2018..AL0001ARTI A ON S.F6_CCODIGO=a.AR_CCODIGO
WHERE C.F5_CESTADO<>'A' AND S.F6_CTD IN ('FT','BV')
AND YEAR(C.F5_DFECDOC)=2018 AND A.AR_CMARCA=@marca 
AND NOT C.F5_CFORVEN IN ('O','P')
GROUP BY A.AR_CCODIGO

UPDATE t SET t.NEU_VENTAS= ISNULL(t2.STOCK,0)FROM @productos t 
LEFT JOIN @stock t2 ON t.CODIGO=t2.CODIGO
DELETE @stock



SELECT * FROM @productos

